### ISSUE TITLE
0.1.2 - scrollbar missing

### ISSUE THREAD

**Issue by Anke** [andy-portmen/font-finder#1]
Hi Andy,
Thank you very much for enhancing FontFinder. I just installed the new version to check it out in FF (current version). Everything is just great and nicely formatted, only a scrollbar is missing, as some of the information provided is cut off at the bottom.
Anke

![fontfinder012](https://cloud.githubusercontent.com/assets/1300920/20866128/0f3e9c6c-ba25-11e6-90c4-d0c67c62d7db.jpg)

**Comment by andy-portmen** [comment]
Thanks for the report. Version 0.1.3 will persist width and height also supports scrollbar.
