### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Neytrino-OnLine** [andy-portmen/font-finder#11]
{
    "app_description": {
        "message": "Лёгкий в использовании инспектор шрифтов, позволяющий просмотреть данные CSS-стилей выделенного элемента"
    },
    "browser_action": {
        "message": "Открыв инспектор (нажатием этой кнопки), переместите указатель мыши на нужный элемент. Чтобы скрыть инспектор - нажмите ESC"
    },
    "context_copy": {
        "message": "Копировать информацию о шрифте"
    },
    "context_embed_mode": {
        "message": "Открыть в прикреплённом режиме"
    },
    "context_find": {
        "message": "Поиск шрифтов в текущем фрейме"
    },
    "context_page": {
        "message": "Инспектировать шрифт"
    },
    "context_replace": {
        "message": "Заменить шрифт"
    },
    "context_selection": {
        "message": "Анализ выделенного"
    },
    "context_window_mode": {
        "message": "Открыть в оконном режиме"
    },
    "window_class": {
        "message": "Класс элемента:"
    },
    "window_color": {
        "message": "Цвет"
    },
    "window_decoration": {
        "message": "Оформление / Трансформации"
    },
    "window_element": {
        "message": "Об элементе"
    },
    "window_font": {
        "message": "Шрифт"
    },
    "window_id": {
        "message": "ID элемента:"
    },
    "window_inspect": {
        "message": "Инспекция:"
    },
    "window_rendered": {
        "message": "Шрифт был подвергнут рендерингу:"
    },
    "window_spacing": {
        "message": "Положение"
    },
    "window_title": {
        "message": "Инспектор :: Font Finder"
    },
    "window_type": {
        "message": "Тип элемента:"
    },
    "options_copy": {
        "message": "Отображать в контекстном меню 'Копировать информацию о шрифте'"
    },
    "options_find": {
        "message": "Отображать в контекстном меню 'Поиск шрифтов в текущем фрейме'"
    },
    "options_page": {
        "message": "Отображать в контекстном меню 'Инспектировать шрифт'"
    },
    "options_replace": {
        "message": "Отображать в контекстном меню 'Заменить шрифт'"
    },
    "options_selection": {
        "message": "Отображать в контекстном меню 'Анализ выделенного'
    },
    "options_faqs": {
        "message": "Открывать страницу FAQ при обновлении"
    },
    "options_support": {
        "message": "Поддержать разработку"
    },
    "options_reset": {
        "message": "Восстановить настройки по умолчанию"
    },
    "options_save": {
        "message": "Сохранить настройки"
    },
    "options_reload": {
        "message": "Перезапуск"
    }
}

**Comment by andy-portmen** [comment]
Thank @Neytrino-OnLine. Would you submit this to https://www.transifex.com/portmen/font-finder/dashboard/
