### ISSUE TITLE
Addon Name error, Popup issue

### ISSUE THREAD

**Issue by meisterleise** [andy-portmen/font-finder#13]
Since this update the Name of this Addon changed to: "Click once to enable the inspector, then move your mouse over the element. Click the ESC key to release the inspector" (Firefox).
That's definitely a too long name! ;-)

The Popup is just a black site if you use it in Firefox fullscreen mode on macOS 14.

**Comment by andy-portmen** [comment]
So does it work as expected on the normal window size? If so switch to the embedded mode which should be compatible with fullscreen (toolbar button -> right-click -> embedded mode)

**Comment by meisterleise** [comment]
Embedded mode works fine!
Any ideas about the long name, too?

**Comment by andy-portmen** [comment]
> Any ideas about the long name, too?

Will be fixed by the next update.
