### ISSUE TITLE
Colors in the Font Finder window are apparently a mix of Firefox colors and custom colors

### ISSUE THREAD

**Issue by cspiegel** [andy-portmen/font-finder#14]
This is Firefox 73.0 and Font Finder 0.3.4.

Problem:

The popup window (when you inspect a font) partially honors the colors from Firefox's preferences, but partially doesn't.  It looks like some text is hardcoded to be black and some backgrounds are hardcoded to be white, while others are taken directly from Firefox's text color settings.

Steps to reproduce:

1. In Firefox's preferences, under "Language and Appearance", click "Colors"
1. Make the foreground red
1. Make the background blue
1. Inspect a font

I'm attaching a screenshot of the result:

![Font Finder](https://user-images.githubusercontent.com/2532775/74559957-61656380-4f1a-11ea-9a5d-64f0068e4dc6.png)

**Comment by andy-portmen** [comment]
Thanks for the report. Should get fixed by the next release.
