### ISSUE TITLE
Bug :(

### ISSUE THREAD

**Issue by mikhoul** [andy-portmen/font-finder#2]
I Use the ESR version of Firefox and I'm not able to install the addon.

http://i.imgur.com/Vrc2GW1.png  

It is caused in part because the there is no ID in the manifest of the addon.

It's not the first time I experience this bug on WebEx , just adding the ID should correct the bug.

Output of the console: http://i.imgur.com/4vAvtNB.png

**Comment by andy-portmen** [comment]
Done in 0.1.7! thanks for the report.
