### ISSUE TITLE
Popup is empty

### ISSUE THREAD

**Issue by gluons** [andy-portmen/font-finder#4]
Font popup shows nothing.

![default](https://user-images.githubusercontent.com/4688092/33240586-d0c24a12-d2ea-11e7-9b56-46baf6a45b1a.png)

**Browser:** Firefox Nightly 59.0a1

**Comment by x-ji** [comment]
Same here. Seems to be a Ubuntu/Linux related bug? Or is it related to newer versions of Firefox. Any updates on this?

**Comment by ashucg** [comment]
Firefox has changed a lot since the FF Quantum release and I think that's the main reason why this issue/bug has appeared. Anyhow, you can simply resize the FontFinder window and things will appear on it. Hope it helps.

[screencast](https://streamable.com/u9e4n)

**Comment by grahamperrin** [comment]
> … Ubuntu/Linux related bug? …

Not reproducible with Waterfox 56.2.1 (64-bit) or Firefox 61.0 (64-bit) with KDE Plasma 5 on FreeBSD-CURRENT, 

```text
$ pkg info waterfox | grep Version ; pkg info firefox | grep Version ; date ; uname -v
Version        : 56.2.1.19_2
Version        : 61.0_1,1
Sat 30 Jun 2018 18:07:16 BST
FreeBSD 12.0-CURRENT #6 r335800: Sat Jun 30 03:35:14 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

I'll test with a different desktop environment …

**Comment by x-ji** [comment]
Seems to be working again now on FF61 with the newest version of the plugin.

**Comment by grahamperrin** [comment]
In the same FreeBSD environment I tested with MATE (couldn't get GNOME 3 to run), couldn't reproduce the issue.
