### ISSUE TITLE
macOS Fullscreen Mode — embed popup in page

### ISSUE THREAD

**Issue by timpulver** [andy-portmen/font-finder#6]
On macOS when browsing in fullscreen mode, the Font Finder opens in a new window, making it impossible to view the font name and the actual rendering of the font side by side.
Would be better to have an overlay like the [What Font OLI](https://addons.mozilla.org/en/firefox/addon/what-font-oli/?src=search) Extension.

**Comment by andy-portmen** [comment]
In version 0.2.1 you can switch to the embedded mode. Use the right-click context menu items over the toolbar button to change the mode.

Thanks for the feature request!
