### ISSUE TITLE
Embedded Mode doesn't work

### ISSUE THREAD

**Issue by nyanpasu64** [andy-portmen/font-finder#7]
I received an update from AMO today. Right-clicking the extension button I can pick Embedded mode, but it doesn't work:

Inspecting: ****

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<tbody>
<tr class="odd">
<td>Color</td>
<td><ul>
<li>color: <span data-obj="color-hex">-</span></li>
<li>color: <span data-obj="color"></span>
<div>

</div></li>
<li>background-color: <span data-obj="background-color-hex">-</span></li>
<li>background-color: <span data-obj="background-color"></span>
<div>

</div></li>
</ul></td>
</tr>
<tr class="even">
<td>Font</td>
<td><ul>
<li>font-family (stack): <span data-obj="font-family"></span></li>
<li>Font being rendered: <a href="#"></a></li>
<li>font-size: <span data-obj="font-size"></span></li>
</ul></td>
</tr>
<tr class="odd">
<td>Spacing</td>
<td><ul>
<li>line-height: <span data-obj="line-height"></span></li>
<li>vertical-align: <span data-obj="vertical-align"></span></li>
<li>letter-spacing: <span data-obj="letter-spacing"></span></li>
<li>word-spacing: <span data-obj="word-spacing"></span></li>
</ul></td>
</tr>
<tr class="even">
<td>Decoration \ Transformation</td>
<td><ul>
<li>font-weight: <span data-obj="font-weight"></span></li>
<li>font-style: <span data-obj="font-style"></span></li>
<li>font-variant: <span data-obj="font-variant"></span></li>
<li>text-transform: <span data-obj="text-transform"></span></li>
<li>text-decoration: <span data-obj="text-decoration"></span></li>
<li>text-align: <span data-obj="text-align"></span></li>
<li>text-indent: <span data-obj="text-indent"></span></li>
</ul></td>
</tr>
<tr class="odd">
<td>Element Details</td>
<td><ul>
<li>Element Type: <span data-obj="element-type"></span></li>
<li>Element ID: <span data-obj="element-id"></span></li>
<li>Element Class: <span data-obj="element-class"></span></li>
</ul></td>
</tr>
</tbody>
</table>

Additionally `Decoration \ Transformation` should be `/` not `\` I think.

**Comment by andy-portmen** [comment]
Thanks! both issues are fixed in the latest release.

**Comment by nyanpasu64** [comment]
Feature request: Press Esc to close the embedded popup.

**Comment by andy-portmen** [comment]
@jimbo1qaz we will have this on the next release. Thanks!

**Comment by nyanpasu64** [comment]
thanks a lot for the feature!
