### ISSUE TITLE
Support for identifying "font being rendered" based on language tags and character-set?

### ISSUE THREAD

**Issue by nyanpasu64** [andy-portmen/font-finder#8]
https://renyuneyun.github.io/Easer/en/ thinks both "font-family" and "font being rendered" are sans-serif, but the font being rendered is "Microsoft YaHei" because of <html lang="zh">

For example, "aaaa𝔞𝔞𝔞𝔞𝙰𝙰𝙰𝙰𞸀𞸀𞸀𞸀" renders symbols from sans-serif, Segoe UI Symbol, and Last Resort (installed on Windows) according to Firefox Inspector "Fonts" tab, but FontFinder says "font being rendered" is Segoe UI, or sans-serif because I'm using Stylus to restyle Github.

**Comment by andy-portmen** [comment]
since I dont have this font installed, please prepare a sample html file like this, and run the font-finder over each node to confirm the issue. Also take an screenshot of the page to compare them visually.

```html
<html xmlns=ihttp://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv=iContent-Type" content="text/html; charset=UTF-8" />
    <title>Untitled Document</title>
  </head>

  <body>
    <ul>
      <li style="font-family: Microsoft YaHei">This is a sample text</li>
      <li style="font-family: sans-serif">This is a sample text</li>
      <li style="font-family: 'Microsoft YaHeii', 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif">This is a sample text</li>
      <li style="font-family: Open Sans">This is a sample text</li>
    </ul>
  </body>
</html>
```

**Comment by nyanpasu64** [comment]
This is more like 2 issues, neither of which are covered by your sample document.

1. Because of characters not present in the first font in a stack, Firefox may display parts of text using fonts lower in the font-family stack, or not present at all. They do not show up in Font Finder.
    - For example, Chinese text (even in stacks consisting purely of "Open Sans" which doesn't support Chinese) is displayed with a Chinese font.
    - Emoji are rendered using an OS-dependent image font. I believe that unlike other Unicode characters, the image font is used even if emoji codepoints are present in the primary font.
    - https://user-images.githubusercontent.com/913957/43033942-1827c718-8c88-11e8-9dd4-8288dec94abb.png

2. Font Finder doesn't "resolve" sans-serif to the actual font used, which varies based on the "lang" setting even on Latin/ASCII characters.
    - https://user-images.githubusercontent.com/913957/43033973-615266f0-8c88-11e8-99bf-b2213bf3d3ed.png

**Comment by andy-portmen** [comment]
So the new release gives a more accurate report by examining all chars individually and displaying the report that contains the usage percentage for each font-family. The only issue that remains is we do not have access to the list of installed fonts in the user's system. As far as I know, there is no way to get this list from within the JS code. At this point, the extension uses a pre-defined set of common fonts to hopefully find the actually parsed font.

Please give it a try and report back!

**Comment by nyanpasu64** [comment]
I honestly don't think this is a good strategy.

![image](https://user-images.githubusercontent.com/913957/43117847-d724bce2-8ec3-11e8-98e9-d1d3db00fdab.png)

If the WebExtensions API is more limited than Firefox Inspector CSS, maybe this issue has no good solution.

**Comment by andy-portmen** [comment]
I found another issue. Would you please try this dev version on both your suggested page and the sample one that I've attached to the ZIP file and report the results.

[test-2.zip](https://github.com/andy-portmen/font-finder/files/2222261/test-2.zip)

To install the developer version, open about:debugging in a browser tab and point the "Load Temporary Addon" to the `webex/manifest.json` file.

**Comment by nyanpasu64** [comment]
Previous screenshot was Kubuntu, now I'm back on Windows 10.

Your sample page works mostly, except it reports Times Roman even though I use a different "serif" font.

If I user Stylus to change \<body>'s font-family to sans-serif, it misreports "Palatino" and "Unknown Font" as sans-serif, even though it's rendered using serif (my fallback font-family is serif).

--------

![image](https://user-images.githubusercontent.com/913957/43132572-1900f1e4-8ef1-11e8-8ff3-bcca6505713f.png)

On https://christianity.stackexchange.com/q/65587 (does not reflect my actual religion), the extension thinks I'm using Times Roman (which does not exist on Windows, it's called Times New Roman). It's actually LusitanaRegular webfont.

--------

my original bug report wasn't quite accurate. On https://renyuneyun.github.io/Easer/en/ , I used the Stylus extension to change <body>'s font-family from Open Sans to sans-serif. Had the page been setup using sans-serif instead of Open Sans, the lang bug would manifest as I described.

**Comment by andy-portmen** [comment]
Please try version 0.3.1. There are some improvements!

**Comment by nyanpasu64** [comment]
Using the addon on this issue page (for example, the comment \<p> tag) causes the tab to freeze for 2 seconds before the popup appears. Version 0.3.0 (possibly your debug version, not sure) was also slow, and displayed a red "x%" emblem on the addon icon during the loading (not shown in 0.3.1).

**Comment by andy-portmen** [comment]
The extension now loads a 20kbytes font file that helps rendering other fonts. This must be the reason of the freezing.; https://github.com/andy-portmen/font-finder/blob/master/webx/data/inject/AND-Regular.otf

I'll compile it as `woff2` later.

**Comment by nyanpasu64** [comment]
Anyway the current state seems to actually work quite well. Thanks!  (still not certain if language specific resolution works)

**Comment by andy-portmen** [comment]
We support a pretty good range of languages; https://github.com/andy-portmen/font-finder/blob/master/webx/data/inject/analyze.js#L5

I am happy with the detection too. The only thing I am still not able to fix is the delay that we have for the first detection in FF.

**Comment by nyanpasu64** [comment]
Oof, it detects the wrong font when performing Google Translate. Note that my `intl.accept_languages` is set to `en-us,en,zh-cn,zh`, causing CJK without a `lang` attribute to default to Microsoft YaHei (Chinese font).

![Meiryo detected as YaHei](https://user-images.githubusercontent.com/913957/44178421-31c86780-a0a7-11e8-9350-f68806f09d43.png)

**Comment by andy-portmen** [comment]
I found that when an `input` element is inspected, we do not return the correct content. This might be the reason why a wrong font is rendered. Can you try the dev version now; https://github.com/andy-portmen/font-finder/tree/master/webx

**Comment by nyanpasu64** [comment]
![fontfinder](https://user-images.githubusercontent.com/913957/44371635-c579a980-a494-11e8-9f9d-c4cb42da9efa.png)
Running Kubuntu again, this shows YaHei despite the font not existing on Linux. Can you fetch fonts from about:config `font.name` and `font.name-list`?

**Comment by andy-portmen** [comment]
As far as I know, there is no way to get the font list as it can be used to identify a computer. I am still investigating.

Please add the font name to the list (https://github.com/andy-portmen/font-finder/blob/master/webx/data/inject/analyze.js#L3) and see if the extension can detect it. It is really weird that it returns the wrong font. It is supposed to return "System Font" if no font matches. We need to solve this.

**Comment by andy-portmen** [comment]
I just pushed a new update. Can you give it a try and see if the font detection is improved or not?
